#!/usr/bin/env bash

set -e

#need to pull in tools and some develoment libraries (texinfo so octave is quiet during 'make check')
yum update -y
yum groupinstall -y "Development tools" \
	&& yum install -y zlib-devel libcurl-devel ncurses-devel readline-devel pcre-devel texinfo

#let's avoid hdd/ssd - optional (need ~5GB)
pp="/shared"
if [ -d "${pp}/build_octave" ]; then
	cd "${pp}/build_octave"
else
	mkdir -p "${pp}" && chmod 777 "${pp}" && mount -o size=5G -t tmpfs tmpfs "${pp}" \
		&& mkdir "${pp}/build_octave" && cp -r * "${pp}/build_octave" && cd "${pp}/build_octave"
fi

#prefix for install
p="/shared/octave" && [ -n "$1" ] && p="$1"
oct="$(basename "${p}")"

#ARCH=processor type for libraries and octave.
# ARCH needs to be a valid option for both gcc -mtune= option and in openBLAS's TargetList.txt (will convert ARCH to upper case for openBLAS)
# ARCH=native will use compiling machine's capabilities
ARCH="native" && [ -n "$2" ] && ARCH="$2"

#go build libraries, octave, squash *.mexa64, install packages and test w/ pkg/test/test.m
./to_build_oct_lib "${p}" "${ARCH}" && cd mex && ./to_build "${p}" && cd ../pkg && ./to_build "${p}" && cd .. \
	&& tar -cJf "../${oct}.log.tar.xz" *.err *.log && cd .. && tar -cJf "${oct}.tar.xz" "${oct}" "${oct}.log.tar.xz" && rm -f "${oct}.log.tar.xz"
